let TransaltionalLanguage = [];
TransaltionalLanguage['Spanish'] = {
    Trace:'Rastro',
    Sketch:'Bosquejo',
    Next:'Próxima',
    onboarding:'inducción',
    TraceandSketch:'Trazar y dibujar',
    usecameratodrawsketch:`Usa una cámara para dibujar Sketch`,
    varioustemplateavailible:`muchas plantillas de rastreo: animales, automóviles, ${"\n"} naturaleza, comida, anime, etc`,
    traceimagesfromgallery:`Convierta una foto a lápiz para dibujar fácilmente`,
    traceimageonpaperwithcameratracing:'Imagen de calco en papel con calco de cámara.',
    camera:'Cámara',
    library:'Biblioteca',
    cute:'Linda',
    viewall:'Ver todo',
    animal:'animal',
    architecture:'Arquitectura',
    cartoon:'Dibujos animados',
    anim:'Animada',
    nature:'Nature',
    noel:'Naturaleza',
    object:'Object',
    people:'Objeto',
    fruits:'frutas',
    continue:'continuar',
    Note:'Nota',
    step_1:'Paso 1',
    step_2:'Paso 2',
    step_3:'Paso 3',
    step_4:'Etapa 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`Después de seleccionar su imagen favorita, la pantalla de seguimiento mostrará el dibujo en la pantalla de su teléfono`,
    start_to_draw:'empezar a dibujar',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'Coloque una hoja de papel en la pantalla y proceda a dibujar la imagen.',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`Coloque su teléfono sobre un vaso de agua de modo que quede paralelo {'\n'} a la mesa`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'La imagen del teléfono estará invertida y podrás dibujarla desde allí.',
    learn_to_draw_in_step_by_step:'Aprende a dibujar paso a paso',
    Trace_image_on_paper_with_camera_tracing:"Imagen de calco en papel con calco de cámara.",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'Active el brillo máximo de la pantalla para mostrar líneas más fácilmente',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'Utilice el modo de bloqueo de pantalla al dibujar para evitar el movimiento',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'El papel de dibujo demasiado grueso no podrá imprimir líneas',
    Drawing:'Dibujo',
    Lession:'Lección',
    Favourites:'Favoritas',
    Work:'Trabajar',
    variou_template:'Varias plantillas',
    availibity:'Disponible',
    trace_image:'Trazar imágenes',
    from_gallery:'de la galería',
    Learn_Draw_Step_Step:`Aprende a dibujar en ${'\n'}Paso a Paso`
},
TransaltionalLanguage['English'] ={
    Trace:'Trace',
    Sketch:'Sketch',
    Next:'Next',
    onboarding:'Onboarding',
    TraceandSketch:'Trace & Sketch',
    usecameratodrawsketch:`Use a camera to draw Sketch`,
    varioustemplateavailible:`lots of tracing templates:Animal , Car, ${"\n"} Nature , Food,Anime etc`,
    traceimagesfromgallery:`Convert to pencil photo for easy drawing`,
    traceimageonpaperwithcameratracing:'Trace image on paper with camera tracing',
    camera:'Camera',
    library:'Library',
    cute:'Cute',
    viewall:'View All',
    animal:'Animal',
    architecture:'Architecture',
    cartoon:'Cartoon',
    anim:'Anim',
    nature:'Nature',
    noel:'Noel',
    object:'Object',
    people:'People',
    fruits:'Fruits',
    continue:'Continue',
    Note:'Note',
    step_1:'Step 1',
    step_2:'Step 2',
    step_3:'Step 3',
    step_4:'Step 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`After selecting your favorite image, the trace screen will show the drawing on your phone's screen`,
    start_to_draw:'Start to Draw',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'Place a piece of paper on the screen & proceed to draw the image',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`Put your phone on a water glass so that it is parallel ${'\n'} to the table`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'The image from the phone will be to inverted, and you can draw it from there',
    learn_to_draw_in_step_by_step:'Learn to draw in Step by Step',
    Trace_image_on_paper_with_camera_tracing:"Trace image on paper with camera tracing",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'Turn on maximum screen brightness to display lines more easily',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'Use screen lock mode when drawing to avoid movement',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'Drawing paper that is too thick will not be able to print lines',
    Drawing:'Drawing',
    Lession:'Lesson',
    Favourites:'Favourites',
    Work:'Work',
    variou_template:'Various Templates',
    availibity:'Available',
    trace_image:'Trace images',
    from_gallery:'from gallery',
    Learn_Draw_Step_Step:`Learn to draw in ${'\n'}Step by Step`
},
TransaltionalLanguage['Urdu'] ={
    Trace:'ٹریس',
    Sketch:'خاکہ',
    Next:'اگلے',
    onboarding:'آن بورڈنگ',
    TraceandSketch:'ٹریس اینڈ اسکیچ',
    usecameratodrawsketch:`خاکہ تیار کرنے کے لیے کیمرہ استعمال کریں۔`,
    varioustemplateavailible:`بہت سارے ٹریسنگ ٹیمپلیٹس:جانور، کار، ${"\n"} فطرت، خوراک، اینیمی وغیرہ`,
    traceimagesfromgallery:`آسانی سے ڈرائنگ کے لیے پنسل تصویر میں تبدیل کریں۔`,
    traceimageonpaperwithcameratracing:'کیمرہ ٹریسنگ کے ساتھ کاغذ پر تصویر ٹریس کریں۔',
    camera:'کیمرہ',
    library:'کتب خانہ',
    cute:'پیارا',
    viewall:'سب دیکھیں',
    animal:'جانور',
    architecture:'فن تعمیر',
    cartoon:'کارٹون',
    anim:'انیم',
    nature:'فطرت',
    noel:'نول',
    object:'چیز',
    people:'لوگ',
    fruits:'پھل',
    continue:'جاری رہے',
    Note:'نوٹ',
    step_1:'مرحلہ نمبر 1',
    step_2:'مرحلہ 2',
    learn_to_draw_in_step_by_step:'مرحلہ وار ڈرا کرنا سیکھیں',
    step_3:'مرحلہ 3',
    step_4:'مرحلہ 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`آپ کی پسندیدہ تصویر منتخب کرنے کے بعد، ٹریس اسکرین آپ کے فون کی اسکرین پر ڈرائنگ دکھائے گی`,
    start_to_draw:'ڈرا کرنا شروع کریں',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'کاغذ کا ایک ٹکڑا اسکرین پر رکھیں اور تصویر کھینچنے کے لیے آگے بڑھیں۔',
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'فون کی تصویر الٹی ہوگی، اور آپ اسے وہاں سے کھینچ سکتے ہیں۔',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`اپنے فون کو پانی کے گلاس پر رکھیں تاکہ یہ میز کے متوازی {'\n'} ہو`,
    Trace_image_on_paper_with_camera_tracing:"کیمرہ ٹریسنگ کے ساتھ کاغذ پر تصویر ٹریس کریں۔",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'آن_زیادہ سے زیادہ_اسکرین_روشنی_سے_ڈسپلے_لائنز_زیادہ_آسانی سے',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'حرکت سے بچنے کے لیے ڈرائنگ کرتے وقت اسکرین لاک موڈ استعمال کریں۔',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'ڈرائنگ پیپر جو بہت موٹا ہے وہ لائنوں کو پرنٹ نہیں کر سکے گا۔',
    Drawing:'ڈرائنگ',
    Lession:'سبق',
    Favourites:'پسندیدہ',
    Work:'کام',
    variou_template:'مختلف ٹیمپلیٹس',
    availibity:'دستیاب',
    trace_image:'تصاویر کو ٹریس کریں۔',
    from_gallery:'گیلری سے',
    Learn_Draw_Step_Step:`${'\n'}مرحلہ وار ڈرا کرنا سیکھیں۔`
},
TransaltionalLanguage['Korea'] ={
    Trace:'추적하다',
    Sketch:'스케치',
    Next:'다음',
    onboarding:'온보딩',
    TraceandSketch:'추적 및 스케치',
    usecameratodrawsketch:`카메라를 사용하여 스케치 그리기`,
    varioustemplateavailible:`다양한 추적 템플릿:동물, 자동차, ${"\n"} 자연, 음식, 애니메이션 등`,
    traceimagesfromgallery:`쉽게 그릴 수 있도록 연필 사진으로 변환`,
    traceimageonpaperwithcameratracing:'카메라 추적으로 종이에 이미지 추적',
    camera:'카메라',
    library:'도서관',
    cute:'귀여운',
    viewall:'모두보기',
    animal:'동물',
    architecture:'건축학',
    cartoon:'만화',
    anim:'애님',
    nature:'자연',
    noel:'남자 이름',
    object:'물체',
    people:'사람들',
    fruits:'과일',
    continue:'계속하다',
    Note:'메모',
    step_1:'1 단계',
    step_2:'2 단계',
    learn_to_draw_in_step_by_step:'단계별로 그리는 법을 배우세요',
    step_3:'3단계',
    step_4:'4단계',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`좋아하는 이미지를 선택하면 추적 화면에서 휴대폰 화면에 그림이 표시됩니다`,
    start_to_draw:'그리기 시작',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'화면에 종이 한 장을 놓고 계속해서 이미지를 그립니다.',
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'휴대폰의 이미지가 반전되어 거기에서 그릴 수 있습니다.',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`테이블과 평행이 되도록 {'\n'} 물컵 위에 휴대전화를 올려놓습니다.`,
    Trace_image_on_paper_with_camera_tracing:"카메라 추적으로 종이에 이미지 추적",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'최대 화면 밝기를 켜면 라인을 더 쉽게 표시할 수 있습니다.',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'움직임을 피하기 위해 그림을 그릴 때 화면 잠금 모드를 사용하세요',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'너무 두꺼운 도화지는 선을 인쇄할 수 없습니다.',
    Drawing:'그림',
    Lession:'수업',
    Favourites:'즐겨찾기',
    Work:'일하다',
    variou_template:'다양한 템플릿',
    availibity:'사용 가능',
    trace_image:'이미지 추적',
    from_gallery:'갤러리에서',
    Learn_Draw_Step_Step:`${'\n'}단계별로 그리는 법을 배워보세요`
},
TransaltionalLanguage['Hindi'] = {
    Trace:'पता लगाना',
    Sketch:'रेखाचित्र',
    Next:'अगला',
    onboarding:'ज्ञानप्राप्ति',
    TraceandSketch:'ट्रेस एवं स्केच',
    usecameratodrawsketch:`स्केच बनाने के लिए कैमरे का उपयोग करें`,
    varioustemplateavailible:`बहुत सारे ट्रेसिंग टेम्प्लेट: जानवर, कार, ${"\n"} प्रकृति, भोजन, एनीमे आदि`,
    traceimagesfromgallery:`आसान ड्राइंग के लिए पेंसिल फोटो में कनवर्ट करें`,
    traceimageonpaperwithcameratracing:'कैमरा ट्रेसिंग के साथ कागज पर छवि ट्रेस करें',
    camera:'कैमरा',
    library:'पुस्तकालय',
    cute:'प्यारा',
    viewall:'सभी को देखें',
    animal:'जानवर',
    architecture:'वास्तुकला',
    cartoon:'कार्टून',
    anim:'अनिम',
    nature:'प्रकृति',
    noel:'नोएल',
    object:'वस्तु',
    people:'लोग',
    fruits:'फल',
    continue:'जारी रखना',
    Note:'टिप्पणी',
    step_1:'स्टेप 1',
    step_2:'चरण दो',
    step_3:'चरण 3',
    step_4:'चरण 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`अपनी पसंदीदा छवि का चयन करने के बाद, ट्रेस स्क्रीन आपके फ़ोन की स्क्रीन पर ड्राइंग दिखाएगी`,
    start_to_draw:'चित्र बनाना प्रारंभ करें',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'स्क्रीन पर कागज का एक टुकड़ा रखें और छवि बनाने के लिए आगे बढ़ें',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`अपने फ़ोन को पानी के गिलास पर रखें ताकि वह टेबल के समानांतर {'\n'} हो`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'फ़ोन से छवि उलटी होगी, और आप इसे वहां से खींच सकते हैं',
    learn_to_draw_in_step_by_step:'चरण दर चरण चित्र बनाना सीखें',
    Trace_image_on_paper_with_camera_tracing:"कैमरा ट्रेसिंग के साथ कागज पर छवि ट्रेस करें",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'लाइनों को अधिक आसानी से प्रदर्शित करने के लिए अधिकतम स्क्रीन चमक चालू करें',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'आंदोलन से बचने के लिए ड्राइंग करते समय स्क्रीन लॉक मोड का उपयोग करें',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'बहुत मोटा ड्राइंग पेपर रेखाएँ मुद्रित नहीं कर पाएगा',
    Drawing:'그림',
    Lession:'수업',
    Favourites:'즐겨찾기',
    Work:'일하다',
    Learn_Draw_Step_Step:`चरण दर चरण ${'\n'}बनाना सीखें`
},
TransaltionalLanguage['French'] = {
    Trace:'Tracer',
    Sketch:'Esquisser',
    Next:'Suivante',
    onboarding:'Intégration',
    TraceandSketch:'Tracer et esquisser',
    usecameratodrawsketch:`Utilisez un appareil photo pour dessiner Sketch`,
    varioustemplateavailible:`de nombreux modèles de traçage : Animal, Voiture, ${"\n"} Nature, Nourriture, Anime, etc.`,
    traceimagesfromgallery:`Convertir en photo au crayon pour un dessin facile`,
    traceimageonpaperwithcameratracing:`Tracer l'image sur papier avec le traçage de la caméra`,
    camera:'Caméra',
    library:'Bibliothèque',
    cute:'Mignonne',
    viewall:'Voir tout',
    animal:'Animale',
    architecture:'Architecture',
    cartoon:'Dessin animé',
    anim:'Animation',
    nature:'Nature',
    noel:'Noël',
    object:'Objet',
    people:'Personnes',
    fruits:'Des fruits',
    continue:'Continuer',
    Note:'Note',
    step_1:'Étape 1',
    step_2:'Étape 2',
    step_3:'Étape 3',
    step_4:'Étape 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`Après avoir sélectionné votre image préférée, l'écran de trace affichera le dessin sur l'écran de votre téléphone`,
    start_to_draw:'Commencer à dessiner',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:`Placez un morceau de papier sur l'écran et procédez au dessin de l'image`,
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`Placez votre téléphone sur un verre d'eau afin qu'il soit parallèle {'\n'} à la table.`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:`L'image du téléphone sera inversée et vous pourrez la dessiner à partir de là.`,
    learn_to_draw_in_step_by_step:'Apprenez à dessiner étape par étape',
    Trace_image_on_paper_with_camera_tracing:"Tracer l'image sur papier avec le traçage de la caméra",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:`Activez la luminosité maximale de l'écran pour afficher les lignes plus facilement`,
    Use_screen_lock_mode_when_drawing_to_avoid_movement:`Utilisez le mode de verrouillage de l'écran lorsque vous dessinez pour éviter tout mouvement`,
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'Un papier à dessin trop épais ne pourra pas imprimer de lignes',
    Drawing:'Dessin',
    Lession:'Leçon',
    Favourites:'Favoris',
    Work:'Travail',
    variou_template:'Divers modèles',
    availibity:'Disponible',
    trace_image:'Images de traces',
    from_gallery:'de la galerie',
    Learn_Draw_Step_Step:`Apprenez à dessiner ${'\n'}étape par étape`
},
TransaltionalLanguage['Portuguese'] = {
    Trace:'Vestígio',
    Sketch:'Esboço',
    Next:'Próxima',
    onboarding:'Integração',
    TraceandSketch:'Rastrear e Esboçar',
    usecameratodrawsketch:`Use uma câmera para desenhar o Sketch`,
    varioustemplateavailible:`muitos modelos de rastreamento:Animal , Car, ${"\n"} Nature , Food,Anime etc.`,
    traceimagesfromgallery:`Converta em foto a lápis para desenhar facilmente`,
    traceimageonpaperwithcameratracing:'Traçar imagem no papel com rastreamento de câmera',
    camera:'Câmera',
    library:'Biblioteca',
    cute:'Bonitinho',
    viewall:'Ver tudo',
    animal:'Animal',
    architecture:'Arquitetura',
    cartoon:'Desenho animado',
    anim:'Animada',
    nature:'Natureza',
    noel:'Noel',
    object:'Objeto',
    people:'Pessoas',
    fruits:'Frutas',
    continue:'Continuar',
    Note:'Observação',
    step_1:'Passo 1',
    step_2:'Passo 2',
    step_3:'etapa 3',
    step_4:'Passo 4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`Após selecionar sua imagem favorita, a tela do traçado mostrará o desenho na tela do seu celular`,
    start_to_draw:'Comece a desenhar',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'Coloque um pedaço de papel na tela e prossiga para desenhar a imagem',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`Coloque seu telefone em um copo d'água de forma que fique paralelo {'\n'} à mesa`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'A imagem do telefone ficará invertida e você poderá desenhá-la a partir daí',
    learn_to_draw_in_step_by_step:'Aprenda a desenhar passo a passo',
    Trace_image_on_paper_with_camera_tracing:"Traçar imagem no papel com rastreamento de câmera",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'Ative o brilho máximo da tela para exibir linhas com mais facilidade',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'Use o modo de bloqueio de tela ao desenhar para evitar movimento',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'Papel de desenho muito grosso não conseguirá imprimir linhas',
    Drawing:'Desenho',
    Lession:'Lição',
    Favourites:'Favoritas',
    Work:'Trabalhar',
    variou_template:'Vários modelos',
    availibity:'Disponível',
    trace_image:'Rastrear imagens',
    from_gallery:'da galeria',
    Learn_Draw_Step_Step:`Apprenez à dessiner ${'\n'}étape par étape`
},
TransaltionalLanguage['Japanese'] = {
    Trace:'痕跡',
    Sketch:'スケッチ',
    Next:'次',
    onboarding:'オンボーディング',
    TraceandSketch:'トレース＆スケッチ',
    usecameratodrawsketch:`カメラを使用してスケッチを描く`,
    varioustemplateavailible:`たくさんのトレース テンプレート:動物、車、${"\n"} 自然、食べ物、アニメなど`,
    traceimagesfromgallery:`簡単に描画できるように鉛筆写真に変換します`,
    traceimageonpaperwithcameratracing:'カメラトレースで紙に画像をトレース',
    camera:'カメラ',
    library:'図書館',
    cute:'かわいい',
    viewall:'すべて見る',
    animal:'動物',
    architecture:'建築',
    cartoon:'漫画',
    anim:'アニム',
    nature:'自然',
    noel:'ノエル',
    object:'物体',
    people:'人々',
    fruits:'果物',
    continue:'続く',
    Note:'注記',
    step_1:'ステップ1',
    step_2:'ステップ2',
    step_3:'3단계',
    step_4:'ステップ4',
    After_selecting_your_favorite_image_the_trace_screen_will_show_the_drawing_on_your_phones_screen:`お気に入りの画像を選択すると、トレース画面に携帯電話の画面に描画が表示されます`,
    start_to_draw:'絵を描き始める',
    Place_a_piece_of_paper_on_the_screen_and_proceed_to_draw_the_image:'화면에 종이 한 장을 놓고 계속해서 이미지를 그립니다.',
    Put_your_phone_on_a_water_glass_so_that_it_is_parallel_to_the_table:`携帯電話をテーブルと平行になるように水グラスの上に置きます。{'\n'}`,
    The_image_from_the_phone_will_be_to_inverted_and_you_can_draw_it_from_there:'휴대폰의 이미지가 반전되어 거기에서 그릴 수 있습니다.',
    learn_to_draw_in_step_by_step:'段階的に絵を描くことを学ぶ',
    Trace_image_on_paper_with_camera_tracing:"カメラトレースで紙に画像をトレース",
    Turn_on_maximum_screen_brightness_to_display_lines_more_easily:'画面の最大輝度をオンにして、線をより簡単に表示します',
    Use_screen_lock_mode_when_drawing_to_avoid_movement:'描画中に動きを避けるために画面ロック モードを使用する',
    Drawing_paper_that_is_too_thick_will_not_be_able_to_print_lines:'画用紙が厚すぎると線が印刷できません',
    Drawing:'描画',
    Lession:'レッスン',
    Favourites:'お気に入り',
    Work:'仕事',
    variou_template:'さまざまなテンプレート',
    availibity:'利用可能',
    trace_image:'トレース画像',
    from_gallery:'ギャラリーから',
    Learn_Draw_Step_Step:`${'\n'}で描画する方法を段階的に学びましょう`
}
export default TransaltionalLanguage