const SET_ROUTE_NAME = 'SET_ROUTE_NAME';
const SELECT_LANGUAGE = "SELECT_LANGUAGE";
const SET_HOME= 'SET_HOME';
const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM'
const SAVE_PHOTO = 'SAVE_PHOTO';
const DELETE_PHOTO= 'DELETE_PHOTO';
const ADD_CUSTOM_IMAGE = 'CUSTOM_IMAGE';
export {
    SET_ROUTE_NAME,
    SELECT_LANGUAGE,
    SET_HOME,
    ADD_ITEM,
    DELETE_ITEM,
    SAVE_PHOTO,
    DELETE_PHOTO,
    ADD_CUSTOM_IMAGE
}